# Generated by Django 4.2.7 on 2025-12-08 12:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('JURY', 'Jury'), ('ADMIN', 'Administrateur')], default='ETUDIANT', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('code_classe', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Classe')),
                ('designation_cl', models.CharField(max_length=200, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('code_cohorte', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Cohorte')),
                ('lib_cohorte', models.CharField(max_length=200, verbose_name='Libellé')),
                ('debut', models.DateField(verbose_name='Date de début')),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code_dpt', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Département')),
                ('designation_dpt', models.CharField(max_length=200, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule_et', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom Complet')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naiss', models.DateField(verbose_name='Date de Naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/', verbose_name='Photo')),
                ('code_cohorte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cohorte', verbose_name='Cohorte')),
                ('id_lgn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code_section', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Section')),
                ('designation_sc', models.CharField(max_length=200, verbose_name='Désignation')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('code_ue', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code UE')),
                ('intitule_ue', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Crédits')),
                ('cmi', models.IntegerField(verbose_name='CMI')),
                ('tp_td', models.CharField(max_length=50, verbose_name='TP/TD')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Semestre')),
            ],
            options={
                'verbose_name': "Unité d'Enseignement",
                'verbose_name_plural': "Unités d'Enseignement",
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('code_jury', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Jury')),
                ('decision', models.TextField(verbose_name='Décision')),
                ('president', models.CharField(max_length=200, verbose_name='Président')),
                ('secretaire', models.CharField(max_length=200, verbose_name='Secrétaire')),
                ('membre', models.CharField(max_length=200, verbose_name='Membre')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe', verbose_name='Classe')),
                ('id_lgn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Jurys',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('matricule_en', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matricule')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom Complet')),
                ('grade', models.CharField(max_length=100, verbose_name='Grade')),
                ('fonction', models.CharField(max_length=100, verbose_name='Fonction')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/', verbose_name='Photo')),
                ('code_dpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departement', verbose_name='Département')),
                ('id_lgn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='EC',
            fields=[
                ('code_ec', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code EC')),
                ('intitule_ue', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('credit', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Crédits')),
                ('cmi', models.IntegerField(verbose_name='CMI')),
                ('tp_td', models.CharField(max_length=50, verbose_name='TP/TD')),
                ('code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ue', verbose_name='UE')),
            ],
            options={
                'verbose_name': 'Élément Constitutif',
                'verbose_name_plural': 'Éléments Constitutifs',
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='code_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe', verbose_name='Classe')),
                ('code_cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cohorte', verbose_name='Cohorte')),
                ('matricule_et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('annee_academique', 'matricule_et')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_ev', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Évaluation')),
                ('cc', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note CC')),
                ('examen', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note Examen')),
                ('rattrapage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note Rattrapage')),
                ('rachat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Note Rachat')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDE', 'Validé'), ('NON_VALIDE', 'Non validé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('code_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ec', verbose_name='EC')),
                ('code_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ue', verbose_name='UE')),
                ('matricule_et', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'unique_together': {('matricule_et', 'code_ue', 'code_ec')},
            },
        ),
    ]
