# Generated by Django 6.0 on 2025-12-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('code_attribution', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Attribution')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('date_attribution', models.DateField(auto_now_add=True, verbose_name="Date d'Attribution")),
                ('code_ec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ec', verbose_name='EC')),
                ('code_ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ue', verbose_name='UE')),
                ('matricule_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['-date_attribution'],
            },
        ),
    ]
