# Generated by Django 6.0 on 2025-12-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attribution'),
        ('reglage', '0002_categorie_fonction_grade_typecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.categorie', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='ue',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.categorie', verbose_name='Catégorie'),
        ),
    ]
