# Generated by Django 6.0 on 2025-12-08 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ec_categorie_ue_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ec',
            name='cmi',
        ),
        migrations.RemoveField(
            model_name='ec',
            name='tp_td',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='cmi',
        ),
        migrations.RemoveField(
            model_name='ue',
            name='tp_td',
        ),
        migrations.AddField(
            model_name='ec',
            name='seuil',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil (%)'),
        ),
        migrations.AddField(
            model_name='ue',
            name='seuil',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil (%)'),
        ),
    ]
