# Generated by Django 6.0 on 2025-12-08 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ec_cmi_remove_ec_tp_td_remove_ue_cmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec',
            name='seuil',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='seuil',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil'),
        ),
    ]
