# Generated by Django 6.0 on 2025-12-08 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ec_seuil_alter_ue_seuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='ue',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classe', verbose_name='Classe'),
        ),
    ]
