# Generated by Django 6.0 on 2025-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ec_classe_ue_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='code_cohorte',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='id',
        ),
        migrations.AddField(
            model_name='inscription',
            name='code_inscription',
            field=models.CharField(default='INS000', max_length=20, primary_key=True, serialize=False, verbose_name='Code Inscription'),
        ),
    ]
