# Generated by Django 6.0 on 2025-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_inscription_code_cohorte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='code_inscription',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Inscription'),
        ),
    ]
