# Generated by Django 6.0 on 2025-12-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_inscription_code_inscription'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='telephone',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.categorie', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='code_dpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.fonction', verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.grade', verbose_name='Grade'),
        ),
    ]
