# Generated by Django 6.0 on 2025-12-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_enseignant_telephone_enseignant_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='id_lgn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur'),
        ),
    ]
