# Generated by Django 6.0 on 2025-12-09 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enseignant_telephone_alter_enseignant_id_lgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='id_lgn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur'),
        ),
    ]
