# Generated by Django 6.0 on 2025-12-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_etudiant_id_lgn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='categorie',
            field=models.CharField(choices=[('A', 'Catégorie A'), ('B', 'Catégorie B')], default='A', max_length=1, verbose_name='Catégorie'),
        ),
    ]
