# Generated by Django 6.0 on 2025-12-09 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ue_categorie'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='ue',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.classe', verbose_name='Classe'),
        ),
    ]
