# Generated by Django 6.0 on 2025-12-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ec_classe_alter_ue_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec',
            name='categorie',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Catégorie'),
        ),
    ]
