# Generated by Django 6.0 on 2025-12-10 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_change_ec_categorie_to_charfield'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec',
            name='seuil',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='code_dpt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.departement', verbose_name='Département'),
        ),
    ]
