# Generated by Django 6.0 on 2025-12-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ec_seuil_alter_enseignant_code_dpt'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='code_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.section', verbose_name='Section'),
        ),
    ]
