# Generated by Django 6.0 on 2025-12-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_enseignant_code_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='code_cohorte',
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nationalite',
            field=models.CharField(choices=[('Congolaise (RDC)', 'Congolaise (RDC)'), ('Congolaise (Congo-Brazzaville)', 'Congolaise (Congo-Brazzaville)'), ('Angolaise', 'Angolaise'), ('Rwandaise', 'Rwandaise'), ('Burundaise', 'Burundaise'), ('Ougandaise', 'Ougandaise'), ('Tanzanienne', 'Tanzanienne'), ('Kenyane', 'Kenyane'), ('Sud-Africaine', 'Sud-Africaine'), ('Camerounaise', 'Camerounaise'), ('Nigériane', 'Nigériane'), ('Sénégalaise', 'Sénégalaise'), ('Ivoirienne', 'Ivoirienne'), ('Gabonaise', 'Gabonaise'), ('Centrafricaine', 'Centrafricaine'), ('Tchadienne', 'Tchadienne'), ('Zambienne', 'Zambienne'), ('Française', 'Française'), ('Belge', 'Belge'), ('Américaine', 'Américaine'), ('Chinoise', 'Chinoise'), ('Indienne', 'Indienne'), ('Autre', 'Autre')], default='Congolaise (RDC)', max_length=100, verbose_name='Nationalité'),
        ),
    ]
