# Generated by Django 6.0 on 2025-12-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cohorte_from_etudiant'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursAttribution',
            fields=[
                ('code_cours', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Cours')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('type_cours', models.CharField(choices=[('UE', "Unité d'Enseignement"), ('EC', 'Élément Constitutif')], max_length=2, verbose_name='Type')),
                ('code_ue_parent', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code UE Parent')),
                ('credit', models.IntegerField(verbose_name='Crédits')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Cours Attribution',
                'verbose_name_plural': 'Cours Attributions',
                'db_table': 'cours_attribution',
            },
        ),
    ]
