# Generated by Django 6.0 on 2025-12-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_create_cours_attribution'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='code_ec',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='code_ue',
        ),
        migrations.AddField(
            model_name='attribution',
            name='code_cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coursattribution', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='type_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.typecharge', verbose_name='Type Charge'),
        ),
    ]
