# Generated by Django 6.0 on 2025-12-11 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_change_code_cours_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='code_cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.coursattribution', verbose_name='Cours'),
        ),
    ]
