# Generated by Django 6.0 on 2025-12-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_revert_code_cours_to_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='code_cours',
            field=models.CharField(default='', max_length=20, verbose_name='Code Cours'),
        ),
    ]
