# Generated by Django 6.0 on 2025-12-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_change_code_cours_to_charfield_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cohorte', verbose_name='Cohorte'),
        ),
    ]
