# Generated by Django 6.0 on 2025-12-11 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_inscription_cohorte'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('rattrapage_actif', models.BooleanField(default=False, verbose_name='Rattrapage activé')),
                ('rachat_actif', models.BooleanField(default=False, verbose_name='Rachat activé')),
                ('date_activation_rattrapage', models.DateTimeField(blank=True, null=True, verbose_name='Date activation rattrapage')),
                ('date_activation_rachat', models.DateTimeField(blank=True, null=True, verbose_name='Date activation rachat')),
                ('active_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Activé par')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe')),
            ],
            options={
                'verbose_name': "Paramètre d'évaluation",
                'verbose_name_plural': "Paramètres d'évaluation",
                'unique_together': {('code_classe', 'annee_academique')},
            },
        ),
    ]
