# Generated by Django 6.0 on 2025-12-12 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_evaluation_cc_alter_evaluation_code_ec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='decision',
            field=models.TextField(blank=True, default='', verbose_name='Décision'),
        ),
        migrations.AlterField(
            model_name='jury',
            name='id_lgn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur'),
        ),
    ]
