# Generated by Django 6.0 on 2025-12-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_jury_decision_alter_jury_id_lgn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuniqueDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('date_deliberation', models.DateField(verbose_name='Date de délibération')),
                ('contenu', models.TextField(blank=True, default='', verbose_name='Communiqué')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Communiqué de délibération',
                'verbose_name_plural': 'Communiqués de délibération',
                'ordering': ['-date_deliberation', '-date_creation'],
                'unique_together': {('code_classe', 'annee_academique', 'date_deliberation')},
            },
        ),
        migrations.CreateModel(
            name='CommentaireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('type_cours', models.CharField(choices=[('UE', 'UE'), ('EC', 'EC')], max_length=2, verbose_name='Type cours')),
                ('code_cours', models.CharField(max_length=20, verbose_name='Code cours')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Commentaire de cours',
                'verbose_name_plural': 'Commentaires de cours',
                'ordering': ['-date_creation'],
            },
        ),
    ]
