# Generated by Django 6.0 on 2025-12-26 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_evaluation_enseignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Fichier PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('disponible', models.BooleanField(default=False, verbose_name='Disponible pour téléchargement')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classe', verbose_name='Classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Bulletin de notes',
                'verbose_name_plural': 'Bulletins de notes',
                'ordering': ['-date_generation'],
                'unique_together': {('etudiant', 'annee_academique', 'code_classe')},
            },
        ),
    ]
