# Generated by Django 6.0 on 2026-01-06 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_bulletinnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('code_recours', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Recours')),
                ('objet', models.CharField(choices=[('mauvaise_transcription_cc', 'Mauvaise transcription de CC'), ('mauvais_calcul', 'Mauvais calcul de la note finale'), ('manque_cote', 'Manque de côte')], max_length=30, verbose_name='Objet du recours')),
                ('ue_ec_concerne', models.CharField(max_length=50, verbose_name='UE/EC concerné(e)')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de traitement'), ('EN_EXAMEN', "En cours d'examen"), ('TRAITE', 'Traité'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('commentaire_traitement', models.TextField(blank=True, verbose_name='Commentaire de traitement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Recours',
                'verbose_name_plural': 'Recours',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='FichierRecours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='recours/', verbose_name='Fichier')),
                ('nom_fichier', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('recours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.recours', verbose_name='Recours')),
            ],
            options={
                'verbose_name': 'Fichier de recours',
                'verbose_name_plural': 'Fichiers de recours',
                'ordering': ['date_ajout'],
            },
        ),
    ]
