# Generated by Django 6.0 on 2026-01-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_recours_fichierrecours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recours',
            name='objet',
            field=models.CharField(choices=[('mauvaise_transcription_cc', 'Mauvaise transcription de CC'), ('mauvaise_transcription_examen', "Mauvaise transcription d'examen"), ('mauvais_calcul', 'Mauvais calcul de la note finale'), ('manque_cote', 'Manque de côte'), ('autre', 'Autre problème')], max_length=30, verbose_name='Objet du recours'),
        ),
    ]
