# Generated by Django 6.0 on 2026-01-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_recours_objet'),
    ]

    operations = [
    ]
