# Generated by Django 6.0 on 2026-01-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_old_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='matricule_et',
            new_name='matricule_etudiant',
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('annee_academique', 'matricule_etudiant')},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='cohorte',
        ),
    ]
