# Generated by Django 6.0 on 2026-01-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_evaluation_matricule_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='cohorte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cohorte', verbose_name='Cohorte'),
        ),
    ]
