# Generated by Django 6.0 on 2026-01-08 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_cohorte_to_inscription'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='code_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe'),
        ),
    ]
