# Generated by Django 6.0 on 2026-01-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_update_communique_classe_foreign_key'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='decision',
        ),
        migrations.AlterField(
            model_name='bulletinnotes',
            name='code_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='jury',
            name='code_classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe'),
        ),
    ]
