# Generated by Django 6.0 on 2026-01-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_update_jury_bulletin_classe_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='decision',
            field=models.TextField(blank=True, null=True, verbose_name='Décision du jury'),
        ),
    ]
