# Generated by Django 6.0 on 2026-01-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_jury_decision'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Notification')),
                ('type_notification', models.CharField(choices=[('COMMUNIQUE', 'Communiqué de délibération'), ('RESULTAT', 'Publication des résultats'), ('EVALUATION', 'Nouvelle évaluation'), ('MESSAGE', 'Message général'), ('SYSTEME', 'Notification système')], max_length=20, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien vers la ressource')),
                ('annee_academique', models.CharField(blank=True, max_length=20, null=True, verbose_name='Année académique')),
                ('code_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.classe', verbose_name='Classe')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
