# Generated by Django 6.0 on 2026-01-10 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_notification'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('session', models.CharField(default='Aout 2025', max_length=100, verbose_name='Session')),
                ('statut', models.CharField(choices=[('present', 'Présent(e)'), ('absent', 'Absent(e)'), ('excuse', 'Excusé(e)')], default='present', max_length=10, verbose_name='Statut')),
                ('date_deliberation', models.DateField(verbose_name='Date de délibération')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations du jury')),
                ('decision_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence décision DG')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('matricule_en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Présence à la délibération',
                'verbose_name_plural': 'Présences aux délibérations',
                'ordering': ['matricule_en__nom_complet'],
                'unique_together': {('code_classe', 'annee_academique', 'matricule_en', 'date_deliberation')},
            },
        ),
    ]
