# Generated by Django 6.0 on 2026-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_presencedeliberation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='decision',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Décision DG (nomination des membres)'),
        ),
    ]
