# Generated by Django 6.0 on 2026-01-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_jury_decision'),
        ('reglage', '0004_alter_anneeacademique_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('type_deliberation', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('ANNEE', 'Année')], max_length=10, verbose_name='Type')),
                ('semestre', models.IntegerField(blank=True, null=True, verbose_name='Semestre')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Données délibérées')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('code_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Délibération',
                'verbose_name_plural': 'Délibérations',
                'unique_together': {('code_classe', 'annee_academique', 'type_deliberation', 'semestre')},
            },
        ),
    ]
