# Generated by Django 4.2.15 on 2026-01-30 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_recreate_deliberation_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliberation',
            unique_together={('matricule_etudiant', 'code_ue', 'code_ec')},
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.RemoveField(
            model_name='deliberation',
            name='annee_academique',
        ),
        migrations.RemoveField(
            model_name='deliberation',
            name='code_classe',
        ),
        migrations.RemoveField(
            model_name='deliberation',
            name='semestre',
        ),
        migrations.RemoveField(
            model_name='deliberation',
            name='type_deliberation',
        ),
    ]
