# Generated by Django 4.2.15 on 2026-01-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0004_alter_anneeacademique_active'),
        ('core', '0045_alter_deliberation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliberation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Année Académique'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='code_classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reglage.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='semestre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semestre'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='type_deliberation',
            field=models.CharField(blank=True, choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('ANNEE', 'Année')], max_length=10, null=True, verbose_name='Type de délibération'),
        ),
        migrations.AlterUniqueTogether(
            name='deliberation',
            unique_together={('matricule_etudiant', 'code_ue', 'code_ec', 'type_deliberation', 'annee_academique')},
        ),
    ]
