# Generated by Django 4.2.15 on 2026-02-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_deliberation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='annee_academique',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Année Académique'),
        ),
    ]
