# Generated by Django 4.2.15 on 2026-02-06 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_annee_academique_to_jury'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression')], max_length=20, verbose_name="Type d'action")),
                ('type_objet', models.CharField(choices=[('Etudiant', 'Étudiant'), ('Enseignant', 'Enseignant'), ('Jury', 'Jury'), ('Inscription', 'Inscription'), ('Attribution', 'Attribution'), ('UE', 'UE'), ('EC', 'EC'), ('Cohorte', 'Cohorte'), ('Classe', 'Classe'), ('Utilisateur', 'Utilisateur'), ('Autre', 'Autre')], max_length=50, verbose_name="Type d'objet")),
                ('objet_id', models.CharField(max_length=100, verbose_name="ID de l'objet")),
                ('objet_nom', models.CharField(max_length=255, verbose_name="Nom/Description de l'objet")),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'action")),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails additionnels')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'Action",
                'verbose_name_plural': "Historiques d'Actions",
                'ordering': ['-date_action'],
            },
        ),
    ]
