# Generated by Django 4.2.15 on 2026-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_historiqueaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('JURY', 'Jury'), ('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('AGENT', 'Agent')], default='ETUDIANT', max_length=20),
        ),
    ]
