# Generated by Django 4.2.15 on 2026-02-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_code_classe_to_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='date_envoi_jury',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi au jury"),
        ),
        migrations.AddField(
            model_name='attribution',
            name='envoye_au_jury',
            field=models.BooleanField(default=False, verbose_name='Envoyé au jury'),
        ),
    ]
