# Generated by Django 6.0.2 on 2026-02-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_evaluation_ancien_cc_evaluation_ancien_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recours',
            name='decision_finale',
            field=models.CharField(blank=True, choices=[('', '---'), ('ACCEPTE', 'Accepté'), ('REJETE', 'Rejeté'), ('PARTIELLEMENT_ACCEPTE', 'Partiellement accepté'), ('SANS_SUITE', 'Classé sans suite')], default='', max_length=30, verbose_name='Décision finale'),
        ),
        migrations.AddField(
            model_name='recours',
            name='traitement_jury',
            field=models.TextField(blank=True, verbose_name='Traitement du jury'),
        ),
    ]
