# Generated by Django 4.2.15 on 2026-02-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0004_alter_anneeacademique_active'),
        ('core', '0054_recours_decision_finale_recours_traitement_jury'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='code_mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reglage.mention', verbose_name='Mention'),
        ),
    ]
