# Generated by Django 4.2.15 on 2026-02-19 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_cohorte_code_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription"),
        ),
    ]
