# Generated by Django 4.2.15 on 2026-02-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0004_alter_anneeacademique_active'),
        ('core', '0056_add_date_inscription_to_inscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jury',
            unique_together={('code_classe', 'annee_academique')},
        ),
    ]
