# Generated by Django 4.2.15 on 2026-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_jury_unique_together_classe_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='password_pres',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe Président'),
        ),
        migrations.AddField(
            model_name='jury',
            name='password_sec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe Secrétaire'),
        ),
    ]
