# Generated by Django 4.2.15 on 2026-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_jury_password_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='jury',
            name='resultat_publie',
            field=models.BooleanField(default=False, verbose_name='Résultats publiés'),
        ),
    ]
