# Generated by Django 4.2.15 on 2026-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_resultat_publie_date_publication_to_jury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionue',
            name='type_inscription',
            field=models.CharField(choices=[('DETTE_COMPENSEE', 'Dette compensée (à reprendre)'), ('DETTE_LIQUIDEE', 'Dette liquidée (capitalisée)')], default='DETTE_COMPENSEE', max_length=30, verbose_name='Type'),
        ),
    ]
