# Generated by Django 6.0.2 on 2026-03-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_dette_liquidee_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ue',
            name='categorie',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='DocumentCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cours', models.CharField(max_length=20, verbose_name='Code Cours')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année Académique')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('type_document', models.CharField(choices=[('COURS', 'Support de cours'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('DESCRIPTIF', 'Descriptif du cours'), ('EXERCICE', 'Exercices'), ('CORRIGE', 'Corrigé'), ('AUTRE', 'Autre')], default='COURS', max_length=20, verbose_name='Type')),
                ('fichier', models.FileField(upload_to='documents_cours/', verbose_name='Fichier PDF')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Document de cours',
                'verbose_name_plural': 'Documents de cours',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
