# Generated by Django 6.0.2 on 2026-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_ue_categorie_documentcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='decision_annuelle',
            field=models.CharField(blank=True, choices=[('ADM', 'Admis'), ('ADMD', 'Admis avec dette'), ('COMP', 'Compensé'), ('AJ', 'Ajourné'), ('DEF', 'Défaillant')], max_length=10, null=True, verbose_name='Décision annuelle'),
        ),
    ]
