# Generated by Django 6.0 on 2025-12-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('code_anac', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Année Académique')),
                ('designation_anac', models.CharField(max_length=200, verbose_name='Désignation Année Académique')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date Début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date Fin')),
                ('active', models.BooleanField(default=False, verbose_name='Année Active')),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'ordering': ['-code_anac'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('code_classe', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Classe')),
                ('designation_classe', models.CharField(max_length=200, verbose_name='Désignation Classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['code_classe'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('code_mention', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Mention')),
                ('designation_mention', models.CharField(max_length=200, verbose_name='Désignation Mention')),
            ],
            options={
                'verbose_name': 'Mention',
                'verbose_name_plural': 'Mentions',
                'ordering': ['code_mention'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('code_niveau', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Niveau')),
                ('designation_niveau', models.CharField(max_length=200, verbose_name='Désignation Niveau')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['code_niveau'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code_section', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Section')),
                ('designation_section', models.CharField(max_length=200, verbose_name='Désignation Section')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['code_section'],
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('code_semestre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Semestre')),
                ('designation_semestre', models.CharField(max_length=200, verbose_name='Désignation Semestre')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['code_semestre'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('code_departement', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Département')),
                ('designation_departement', models.CharField(max_length=200, verbose_name='Désignation Département')),
                ('code_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reglage.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['code_departement'],
            },
        ),
    ]
