# Generated by Django 6.0 on 2025-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('code_categorie', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Catégorie')),
                ('designation_categorie', models.CharField(max_length=200, verbose_name='Désignation Catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['code_categorie'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('code_fonction', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Fonction')),
                ('designation_fonction', models.CharField(max_length=200, verbose_name='Désignation Fonction')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['code_fonction'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('code_grade', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Grade')),
                ('designation_grade', models.CharField(max_length=200, verbose_name='Désignation Grade')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['code_grade'],
            },
        ),
        migrations.CreateModel(
            name='TypeCharge',
            fields=[
                ('code_type', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Type')),
                ('designation_typecharge', models.CharField(max_length=200, verbose_name='Désignation Type Charge')),
            ],
            options={
                'verbose_name': 'Type de Charge',
                'verbose_name_plural': 'Types de Charge',
                'ordering': ['code_type'],
            },
        ),
    ]
