# Generated by Django 6.0 on 2025-12-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0002_categorie_fonction_grade_typecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='code_mention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reglage.mention', verbose_name='Mention'),
        ),
        migrations.AddField(
            model_name='classe',
            name='code_niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reglage.niveau', verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='code_classe',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Code Classe'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='designation_classe',
            field=models.CharField(max_length=400, verbose_name='Désignation Classe'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('code_niveau', 'code_mention')},
        ),
    ]
