# Generated by Django 6.0 on 2025-12-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglage', '0003_classe_code_mention_classe_code_niveau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneeacademique',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Année en cours'),
        ),
    ]
